# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- '*'

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: ms-devlabs.vsts-developer-tools-build-tasks.tfx-installer-build-task.TfxInstaller@1
  displayName: 'Use Node CLI for Azure DevOps: v0.6.x'

- task: ms-devlabs.vsts-developer-tools-build-tasks.extension-version-build-task.ExtensionVersion@1
  displayName: 'Query Extension Version'
  inputs:
    connectedServiceName: Marketplace
    publisherId: chwebdude
    extensionId: 'dev-ops-stream '
    versionAction: Patch
    setBuildNumber: true


- task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@2
  displayName: 'Use Yarn 1.x'
  inputs:
    checkLatest: true

- task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@2
  displayName: 'Yarn  restore'


- task: bool.compile-type-script.compile-type-script-task.compile-type-script@1
  displayName: 'Compile TypeScript buildtab'  

- task: ms-devlabs.vsts-developer-tools-build-tasks.package-extension-build-task.PackageVSTSExtension@1
  displayName: 'Package Extension: vss-extension.json'

- task: ms-devlabs.vsts-developer-tools-build-tasks.publish-extension-build-task.PublishExtension@1
  displayName: 'Publish Extension'
  inputs:
    connectedServiceName: Marketplace
    # extensionName: 'dependency-checker-dev'
    extensionVersion: '$(Build.BuildNumber)'
    # updateTasksId: true
    extensionVisibility: private
    shareWith: webdude
    noWaitValidation: true
  continueOnError: true
  # condition: ne(variables['Build.SourceBranch'], 'refs/heads/master')
